FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY target/ValidationService-0.0.1-SNAPSHOT.jar ValidationService-0.0.1-SNAPSHOT.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "ValidationService-0.0.1-SNAPSHOT.jar"]
